### ISSUE TITLE
Should charttimes in the TOTALBALEVENTS table always equal 11pm?

### ISSUE THREAD

**Issue by tompollard** [mimic2/v3.0#10]
It looks like the charttime listed in the TOTALBALEVENTS table is always equal to 11pm (although this should be checked). If an accurate time is not available, should it be dropped?

**Comment by mornin** [comment]
Yes. Total balance data were supposed to be recorded daily. It was our decision since v2.6 that all total events records will be time stamped to 11am.

**Comment by mornin** [comment]
I propose no changes would be needed.
