### ISSUE TITLE
demographic_detail CSV missing in physionet download

### ISSUE THREAD

**Issue by parisni** [mimic2/v3.0#102]
Hello,

They are only 23 tables to download in this link https://physionet.org/works/MIMICIIIClinicalDatabase/files/

Apparently demographic_detail is missing

Thanks!

Nicolas

**Comment by SvenVanPoucke** [comment]
Hi,
MIMICIII might be different from MIMICII v3.0 right?
Is the complete database accessible on a server?
Cheers
Sven

2015-09-06 20:42 GMT+02:00 Paris Nicolas <notifications@github.com>:

> Hello,
>
> They are only 23 tables to download in this link
> https://physionet.org/works/MIMICIIIClinicalDatabase/files/
>
> Apparently demographic_detail is missing
>
> Thanks!
>
> Nicolas
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mimic2/v3.0/issues/102>.
>



-- 
Dr. Sven Van Poucke
Ziekenhuis Oost-Limburg
Schiepse Bos 6
3600 Genk
[image: LinkedIn] <http://www.linkedin.com/pub/sven-van-poucke/60/847/aa2>

[image: Share on ResearchGATE]
<https://www.researchgate.net/profile/Sven_Van_Poucke/>

**Comment by tompollard** [comment]
Hi @SvenVanPoucke and @parisni,

The latest version of MIMIC (MIMIC-III version 1.0) is available as flat CSV files on PhysioNet at:
https://physionet.org/works/MIMICIIIClinicalDatabase/

We are working on documentation and will make it available as soon as possible. The content available via this repository is outdated and will be removed shortly to prevent confusion.

Best wishes,
Tom
---
Tom Pollard

Postdoctoral Researcher,
MIT Laboratory for Computational Physiology,
Institute for Medical Engineering and Science,
E25-545B, 45 Carleton St, Cambridge, MA 02142
---
