### ISSUE TITLE
MIMIC II Diseases Information 

### ISSUE THREAD

**Issue by peymangh** [mimic2/v3.0#103]
I have a problem in MIMIC II clinical database explorer. I want to find disease information of each patient in this database but I don't know how I should do that. I will be grateful if you help me.
for example, I want information about patients who had Sepsis disease, what should I do?
Thanks;

**Comment by tompollard** [comment]
Hello @peymangh, and thanks for your message. We are in the process of releasing a new version of the MIMIC along with a support forum, which when it is ready will be the best place to get an answer to your question.

In the meantime, my suggestion for using the MIMIC II explorer would be to refer to the PDF documentation at: http://mimic.physionet.org/UserGuide/UserGuide.pdf

There are different ways of defining sepsis, so we recommend collaborating with a clinical expert to choose the most appropriate method. You might want to look at: http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3609896/ which uses the Angus criteria to select a sepsis group.

**Comment by peymangh** [comment]
Thanks Dear @tompollard.
