### ISSUE TITLE
Rename time-related columns in the NOTEEVENTS table 

### ISSUE THREAD

**Issue by tompollard** [mimic2/v3.0#17]
The NOTEEVENTS table includes:

- charttime
- realtime

The columns should be renamed:

- charttime => TIME
- realtime => KEYINTIME

Relates to issue #5

**Comment by tompollard** [comment]
Done. Columns updated in mimic2v30b_utc: 

``` sql
create table mimic2v30b_utc.NOTEEVENTS as
select 
REC_ID
,SUBJECT_ID
,HADM_ID
,ICUSTAY_ID
,ELEMID
,cast(CHARTTIME AT TIME ZONE 'UTC' as timestamp) as TIME
,cast(REALTIME AT TIME ZONE 'UTC' as timestamp) KEYINTIME
,CGID
,CORRECTION
,CUID
,CATEGORY
,TITLE
,TEXT
,EXAM_NAME
,PATIENT_INFO
,NOTEEVENTSDATAID
from mimic2v30b.NOTEEVENTS;
```

**Comment by mornin** [comment]
Refer to issue #5 for the most updated column name.

STORETIME column was removed, for it is null for every row.
