### ISSUE TITLE
Should tables reference CG_UNIQUEID instead of CGID?

### ISSUE THREAD

**Issue by tompollard** [mimic2/v3.0#2]
CGID in the D_CAREGIVERS table is not unique. Should foreign keys that reference CGID (additives, chartevents) instead reference the new CG_UNIQUEID?

**Comment by mornin** [comment]
I think so. We should check the uniqueness of both IDs to confirm though.

**Comment by tompollard** [comment]
See documentation at: http://mimic2.github.io/v3.0/dat/dcaregivers.html

"For the multiple CGIDs for one Care Giver, we chose one ID as the active one and assigned status ‘A’ (*A*ctive) in the CGID_STATUS column, all other CGIDs were assigned status ‘M’ (*M*erged), indicating a ‘merged’ status of the CGID. Only the CGID with CGID_status=’A’ was used in other tables like MEDEVENTS, CHARTEVENTS, etc."

...so no changes are required. Close issue.
