### ISSUE TITLE
Timezone is not supported by MySQL

### ISSUE THREAD

**Issue by mornin** [mimic2/v3.0#27]
In the version mimic2v30b@brp2, all time stamps were stored as data type "time stamp with time zone", and the time zone was set as Newyork/US. However, some other DBMS platforms (e.g. MySQL) may not support time zone information for the time stamp data type.

**Comment by mornin** [comment]
Proposed solution: convert and unify all time stamps in mimic2v30b@brp2 to time zone to 'UTC', then remove all the time zone information. This can be done by a query like:

cast(INTIME AT TIME ZONE 'UTC' as timestamp) as INTIME

**Comment by tompollard** [comment]
All times case to UTC in mimic2v30b_utc
