### ISSUE TITLE
Merge label and cumlabel in TOTALBALEVENTS table?

### ISSUE THREAD

**Issue by tompollard** [mimic2/v3.0#3]
Should the label and cumlabel fields be merged? They appear to be the same.

**Comment by mornin** [comment]
The label column in the TOTABALEVENTS table was inherited from V26. The cumlabel are the new labels merged from the METAVISON data. We should merge them. Since most of the time, one of them is null.

**Comment by tompollard** [comment]
labels are either stored in the label column or the cumlabel column. 

The following query returns 0 rows:
SELECT *
FROM totalbalevents
where label is not null and cumlabel is not null

The following query returns 0 rows:
SELECT *
FROM totalbalevents
where label is null and cumlabel is null

The following query returns many rows:
SELECT *
FROM totalbalevents
where label is null and cumlabel is not null

**Comment by tompollard** [comment]
Our decision is to merge the cumlabel column into the labels column.

, CASE WHEN label is null then cumlabel ELSE label END as label;
