### ISSUE TITLE
ORDERENTRY.PATIENTWEIGHT: how comes 10 patients are over 710 kg?

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [mimic2/v3.0#35]
`ORDERENTRY.PATIENTWEIGHT` is the patient's weight expressed in grams. How comes 10 patients are over 710 kg?

```sql
SELECT DISTINCT ORDERENTRY.SUBJECT_ID, ORDERENTRY.PATIENTWEIGHT
FROM MIMIC2V30.ORDERENTRY
ORDER BY ORDERENTRY.PATIENTWEIGHT DESC;
```

![image](https://cloud.githubusercontent.com/assets/15331/7383047/2f2578b4-ede6-11e4-8607-852c89966ad3.png)

**Comment by tompollard** [comment]
If entered into the system correctly then PATIENTWEIGHT measurements in the new ORDERENTRY table should be in grams. It may be that for some patients the weight was recorded incorrectly (e.g. a typing error, a really bad guess, or a measurement in pounds).

Taking the first subject_id in your list as an example and running the following query:

``` sql
SELECT orderid, subject_id, icustay_id, patientweight
FROM MIMIC2V30.ORDERENTRY
where subject_id = 25757
order by issuedate
```
returns the following results:

ORDERID | SUBJECT_ID | ICUSTAY_ID | PATIENTWEIGHT
--- | --- | --- | --- | ---
967114 | 25757 | 60119 | 1410000
967128 | 25757 | 60119 | 1410000
967239 | 25757 | 60119 | 141000
967301 | 25757 | 60119 | 141000

So in this case, the patientweight appears to have been erroneously recorded as 1410000 grams, then amended to 141000 grams in a later order. I randomly selected another subject_id from your list (subject_id = 26220), which showed the same pattern.

**Comment by tompollard** [comment]
The following query produces a distribution of the average weight of each subject_id in the ORDERENTRY table:

``` sql
select bucket, count(*) from (
select subject_id, avg(patientweight), width_bucket(avg(patientweight), 20000, 220000, 10) as
bucket from mimic2v30.ORDERENTRY 
where patientweight is not null
group by subject_id
) group by bucket order by bucket;
```

The results look like this (range added manually):

BUCKET | RANGE (>= base value) | COUNT
--- | --- | ---
1 | <20,000 | 7
2 | 20,000-40,000 | 91
3 | 40,000 - 60,000 | 2118
4 | 60,000 - 80,000 | 5711
5 | 80,000 - 100,000 | 4426
6 | 100,000 - 120,000 | 1772
7 | 120,000 - 140,000 | 516
8 | 140,000 - 160,000 | 163
9 | 160,000 - 180,000 | 61
10 | 180,000 - 200,000 | 23
11 | 200,000 - 220,000 | 17
12 | >=220,000 | 3831 | 29

So the most common weight range is 60-80kg, which seems right. 

An alternative source of weight is the MIMIC2V30.CHARTEVENTS table (after a lookup for itemids in the D_ITEMS table). 

I'll need to get more detail about the tables to be able to suggest which approach to finding weight would be most reliable (@mornin). One thing to consider is that ORDERENTRY is a new table, so I would expect it to only include weight data for patients added since the V2.6 release.

**Comment by Franck-Dernoncourt** [comment]
Good point, thanks. In an ideal world, the software used to input values that aren't supposed to drastically change overnight should check for outstanding variations when the medical staff input new values.

The MIMIC2V30.CHARTEVENTS table does indeed seem to contain some interesting information regarding the weights:

```sql
SELECT D_ITEMS.LABEL, COUNT(UNIQUE(CHARTEVENTS.ICUSTAY_ID)) 
FROM MIMIC2V30.CHARTEVENTS, MIMIC2V30.D_ITEMS
WHERE LOWER(D_ITEMS.LABEL) LIKE '%weight%'
AND D_ITEMS.ITEMID = CHARTEVENTS.ITEMID
GROUP BY D_ITEMS.LABEL
;
```

| "LABEL"                              | "COUNT(UNIQUE(CHARTEVENTS.ICUSTAY_ID))" | 
|--------------------------------------|-----------------------------------------| 
| "Weight Change"                      | 14876                                   | 
| "Weight Kg"                          | 381                                     | 
| "Daily Weight"                       | 29740                                   | 
| "Previous Weight"                    | 18436                                   | 
| "Birthweight (kg)"                   | 7719                                    | 
| "Unintentional weight loss >10 lbs." | 9798                                    | 
| "Feeding Weight"                     | 1964                                    | 
| "ideal body weight"                  | 1                                       | 
| "Previous Weight (kg)"               | 3807                                    | 
| "Admission Weight (lbs.)"            | 16291                                   | 
| "Weight Change  (gms)"               | 3803                                    | 
| "Birth Weight    (kg)"               | 4601                                    | 
| "Present Weight  (lb)"               | 4358                                    | 
| "Present Weight  (kg)"               | 4358                                    | 
| "Present Weight  (oz)"               | 4358                                    | 
| "Previous WeightF"                   | 21130                                   |

**Comment by tompollard** [comment]
> In an ideal world, the software used to input values that aren't supposed to drastically change overnight should check for and warn against outstanding variations when the medical staff input new values.

Agreed! It's tempting to fix the obvious errors (like the 710kg patient), but our policy is to leave the data in its original form. 

While cleaning up all of the noise wouldn't necessarily be a good thing, it is useful for everyone to understand the limitations of the data. Perhaps we need to find a way of indicating data quality...

**Comment by Franck-Dernoncourt** [comment]
(still present in MIMIC-III:

```sql
SELECT DISTINCT PATIENTWEIGHT, SUBJECT_ID 
FROM  mimiciii.ioevents 
ORDER BY PATIENTWEIGHT DESC ;
```

![image](https://cloud.githubusercontent.com/assets/15331/10983741/651262ce-83e2-11e5-8ec2-c8b17459527f.png)




)
