### ISSUE TITLE
How to know through which ICUs a patient went through during a given hospital stay?

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [mimic2/v3.0#39]
The table MIMIC2V30.ADMISSIONS contains two columns `FIRST_SERVICE` and `LAST_SERVICE` that indicate the first service unit and last service unit of a hospital stay. Is there any way to see which service unit(s) a patient went through between the first service unit and the last service unit during a given hospital stay? I'm basically looking for patients' paths during their hospital stays, e.g. MICU->SICU->CCU.

I see that over 10% of hospital admissions had a different first service unit and last service unit (and it ignores patients who might have done X->Y->X):

```sql
-- result: 0.116
WITH cnt1 AS
  (SELECT COUNT(DISTINCT(ADMISSIONS.HADM_ID)) count_2_or_more
  FROM MIMIC2V30.ADMISSIONS
  WHERE FIRST_SERVICE <> LAST_SERVICE
  ),
  cnt2 AS
  (SELECT COUNT(DISTINCT(ADMISSIONS.HADM_ID)) count_total_admissions
  FROM MIMIC2V30.ADMISSIONS
  )
SELECT cnt1.count_2_or_more/cnt2.count_total_admissions FROM cnt1, cnt2;
```

**Comment by Franck-Dernoncourt** [comment]
Whoops, this issue can be closed, sorry I had forgotten about that table MIMIC2V30.CENSUSEVENTS, which seem to contain all information pertaining to traveling from care units to care units:

```sql
SELECT * FROM MIMIC2V30.CENSUSEVENTS
WHERE ICUSTAY_ID = 6134
ORDER BY INTIME ASC;

SELECT  ICUSTAY_ID,  COUNT(*) cnt  FROM MIMIC2V30.CENSUSEVENTS
GROUP BY ICUSTAY_ID
ORDER BY cnt DESC;
```

In theory FIRST_SERVICE and LAST_SERVICE could be other services than care units, since there is no primary key in these two columns, but I guess for now we can safely assume that they are always care units.

```sql
SELECT FIRST_SERVICE,  COUNT(*) 
FROM MIMIC2V30.ADMISSIONS
GROUP BY FIRST_SERVICE;
```

| "FIRST_SERVICE" | "COUNT(*)" | 
|-----------------|------------| 
| ""              | 1977       | 
| "SICU"          | 13121      | 
| "MICU"          | 22835      | 
| "NICU"          | 7941       | 
| "CCU"           | 7298       | 
| "CSRU"          | 4783       | 


```sql
SELECT LAST_SERVICE,  COUNT(*) 
FROM MIMIC2V30.ADMISSIONS
GROUP BY LAST_SERVICE;
```

| "LAST_SERVICE" | "COUNT(*)" | 
|----------------|------------| 
| ""             | 1978       | 
| "SICU"         | 12969      | 
| "MICU"         | 22354      | 
| "NICU"         | 7941       | 
| "CCU"          | 5363       | 
| "CSRU"         | 7350       | 

(interesting to see that for ~2000 HADM_ID, FIRST_SERVICE  is empty, and for ~2000 HADM_ID, LAST_SERVICE  is empty).

**Comment by tompollard** [comment]
Thanks again Franck, and no need to apologise! These posts will be helpful for other researchers too.

> In theory FIRST_SERVICE and LAST_SERVICE could be other services than care units, since there is no primary key in these two columns, but I guess for now we can safely assume that they are always care units.

The omission of a key for the FIRST_SERVICE and LAST_SERVICE in the ADMISSIONS table is a useful point to note. I think it's safe to assume that the services listed ("CCU", "NICU" etc) refer to the careunits in the D_CAREUNITS table, but I'll check and will update you here if not (@mornin, should we add the keys?).

> (interesting to see that for ~2000 HADM_ID, FIRST_SERVICE is empty, and for ~2000 HADM_ID, LAST_SERVICE is empty).

It looks like the numbers are similar because the omissions are paired (i.e. patients whose FIRST_SERVICE is null almost always have null for LAST_SERVICE too). The following query counts 1977 rows:

``` sql
SELECT count(*)
FROM MIMIC2V30.admissions
WHERE first_service is null
and last_service is null 
```
I'm not sure why this information isn't recorded, but it would be interesting to look into.

**Comment by Franck-Dernoncourt** [comment]
In MIMIC-III, the table `transfer` contains that information:

![image](https://cloud.githubusercontent.com/assets/15331/10984491/d434f68a-83e7-11e5-9f81-c4cf63dee568.png)
