### ISSUE TITLE
Data from A_MEDDURATIONS table is not included in v3.0

### ISSUE THREAD

**Issue by tompollard** [mimic2/v3.0#4]
In v2.6, the A_MEDDURATIONS table includes durations of med events. The table has been removed in v3.0, but the data does not appear to have been completely merged.

Should we merge the data into the MEDEVENTS table? How should we do this?

**Comment by mornin** [comment]
Yes. Let's merge the duration information from v26.A_MEDDURATIONS to v30.MEDEVENTS table.

**Comment by tompollard** [comment]
Potential challenges is that date mapping has changed between v2.6 and v3.0, so dates in v2.6 may not relate to dates in v3.0...

**Comment by tompollard** [comment]
Shift is the same...no problem :)

**Comment by mornin** [comment]
Confirmed that time shifts for v2.6 and v3.0 are compatible.

The following query outputs 0 as time difference. 
select a.hadm_id
, a.admit_dt-b.admit_dt as diff
from MIMIC2V30B.admissions a
join mimic2v26.admissions b on a.hadm_id=b.hadm_id
order by 2 desc;
