### ISSUE TITLE
Out of memory error when querying MIMIC2 V3.0-alpha1 on TESLA server

### ISSUE THREAD

**Issue by tompollard** [mimic2/v3.0#47]
Several users (inc. @Franck-Dernoncourt ) have reported the following error, or similar, when attempting to access/query MIMIC2 V3.0-alpha1 (test database) on the TESLA server:

```
ORA-04031: unable to allocate 3896 bytes of shared memory ("shared pool","select *
from mimic2v30.d_pa...","sga heap(4,0)","kglsim object batch")
04031. 00000 -  "unable to allocate %s bytes of shared memory (\"%s\",\"%s\",\"%s\",\"%s\")"
*Cause:    More shared memory is needed than was allocated in the shared
           pool.
*Action:   If the shared pool is out of memory, either use the
           dbms_shared_pool package to pin large packages,
           reduce your use of shared memory, or increase the amount of
           available shared memory by increasing the value of the
           INIT.ORA parameters "shared_pool_reserved_size" and
           "shared_pool_size".
           If the large pool is out of memory, increase the INIT.ORA
           parameter "large_pool_size".
```

@mornin @li-lcp

**Comment by Franck-Dernoncourt** [comment]
(copying the email for logging purpose)

The issue first appeared when I was executing a bunch of UPDATE statements (~50K, around ~30K got executed and committed before the issue appeared). This made me think that the SQL area on Oracle DB grew too much to the point of maxing out the shared pool's memory. In theory though if there's no room left in the SQL area cache, older statements are aged out, so I'm quite surprised.

Running the follow query would confirm it, but ironically and unsurprisingly I get the ORA-04031 error on it as well:
```sql
SELECT * FROM (
SELECT name, bytes/(1024*1024) MB FROM v$sgastat  
WHERE  pool = 'shared pool'  ORDER BY bytes DESC)
WHERE rownum < 11;
```

I would tend to think that flushing the share pool should solve the issue (or increasing the shared pool size as Melek suggested):
```sql alter system flush shared_pool;```

**Comment by mornin** [comment]
It seems like your query/some other query has max out the processing power and memory of the server. I tried to terminate the queries, but I failed, for the server has no additional memory for any requests anymore. I will need to shutdown and restart tesla now.

**Comment by Franck-Dernoncourt** [comment]
Thanks, do you know what happened? (just so that I can try avoiding causing the issue again)

**Comment by mornin** [comment]
Hi Frank,

The server has been restarted. We have investigated the problem. It does seem like your update query is the one that caused the problem. Although your query looks like a simple query, the UPDATE command requires some consistency check and locking of tables. These may have caused the issue. I suggest creating a new table may be a better approach.

In addition, due to the forced shutdown, your COHORT_A table has been corrupted. Hope you may regenerate the table again.
