### ISSUE TITLE
Inconsistent terminology used for times

### ISSUE THREAD

**Issue by tompollard** [mimic2/v3.0#5]
Several different terms used to describe time, including:
time, charttime, realtime, starttime, endtime.

This can be confusing (for example, see the medevents table) and introduces extra complexity to queries. If possible, terms should be consolidated.

**Comment by tompollard** [comment]
In the NOTEEVENTS table, charttime and realtime should be renamed to the new time, timevalidated terminology.

**Comment by tompollard** [comment]
Clearer terminology is: 

CHARTTIME => TIME
REALTIME => TIMEOFENTRY (rather than VALIDATIONTIME as initially suggested).

**Comment by tompollard** [comment]
We have attempted to consolidate terminology for time-related columns. The issue of whether "TIME" is an appropriate column name will be dealt with separately (in issue #23 for now).

**Comment by mornin** [comment]
In the v30_release schema, here are the latest naming for time stamp and date  in the database:

CHARTTIME (remained as it is)
REALTIME / KEYINTIME => STORETIME
DATE => CHARTDATE
