### ISSUE TITLE
Code to generate LCP_DAILY_SOFA

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [mimic2/v3.0#51]
Could you please share the code to generate `LCP_DAILY_SOFA`?

**Comment by mornin** [comment]
Good suggestion! I will organize the code and upload them to our github repo.

**Comment by mornin** [comment]
Codes for SOFA, SAPS-I and ELIXHAUSER severity scores calculation have been uploaded to https://github.com/mimic2/v3.0/tree/gh-pages/code/severity_scores

**Comment by Franck-Dernoncourt** [comment]
Thanks!
