### ISSUE TITLE
All patients over age 90 are shifted to an older age: seems to affect patients slightly below 90 as well

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [mimic2/v3.0#52]
I read in the [description of table D_PATIENTS](http://mimic2.github.io/v3.0/dat/dpatients.html) that:

> Another change to this table is that we shifted the ages of all patients over age 90 to an older age (over 200) for de-identification purposes.

However, it seems like patients slightly below 90 are also shifted: the query below shows that no non-shifted patients were aged over 89.5 years:

```sql
SELECT ADMISSIONS.SUBJECT_ID, ADMISSIONS.HADM_ID, 
(CAST(ADMISSIONS.ADMIT_DT AS DATE) - D_PATIENTS.DOB)/365.25 age_at_admission,
ADMISSIONS.ADMIT_DT, CAST(ADMISSIONS.ADMIT_DT AS DATE), D_PATIENTS.DOB
FROM  MIMIC2V30.ADMISSIONS, MIMIC2V30.D_PATIENTS
WHERE D_PATIENTS.SUBJECT_ID = ADMISSIONS.SUBJECT_ID  
ORDER BY age_at_admission DESC;

 ```
![image](https://cloud.githubusercontent.com/assets/15331/7485612/a37603de-f366-11e4-9267-c7fd0022e1e3.png)

Did I miss something? When is the age measured? I tried to run the same query with age at hospital discharge time but get something similar:

```sql
SELECT ADMISSIONS.SUBJECT_ID, ADMISSIONS.HADM_ID, 
(CAST(ADMISSIONS.DISCH_DT AS DATE) - D_PATIENTS.DOB)/365.25 age_at_admission,
ADMISSIONS.DISCH_DT, D_PATIENTS.DOB
FROM  MIMIC2V30.ADMISSIONS, MIMIC2V30.D_PATIENTS
WHERE D_PATIENTS.SUBJECT_ID = ADMISSIONS.SUBJECT_ID  
ORDER BY age_at_admission DESC;
```

**Comment by mornin** [comment]
This has been explained in detailed on the FAQ page of MIMIC-II. You may find the link here:
http://mimic.physionet.org/database/faqs.html#21

**Comment by Franck-Dernoncourt** [comment]
Sorry I must have missed something: why is there no patient aged between 89.5 years and 90 years at the time of their hospital admission?

**Comment by tompollard** [comment]
Yes, this is odd. On my list of things to look into...

**Comment by alistairewj** [comment]
This is expected behaviour. The de-identification defines age as

```sql
round((a.adm_dt-dp.dob)/365.242,0)
```

This causes ages < 89.5 to be rounded down, and not be de-identified, and ages >= 89.5 to be rounded up and subsequently de-identified. We may redefine this in a future release.
