### ISSUE TITLE
sequence_num in PROCEDUREEVENTS table appears to be incorrect

### ISSUE THREAD

**Issue by tompollard** [mimic2/v3.0#6]
The sequence_num in the PROCEDUREEVENTS table is intended to "indicate the chronological order of this event, relative to the other events for the same patient and hospital admission (lower equates to earlier)."

...but the sequence_num does not appear to reflect the sequence of events when ordered by date. If we cannot clearly explain the meaning of sequence_num, the field should be removed.

**Comment by tompollard** [comment]
Discussion with Mornin. Meaning of sequence_num is unclear and potentially misleading. Removed.

**Comment by Franck-Dernoncourt** [comment]
Just to give an example showing that `PROCEDUREEVENTS.SEQUENCE_NUM`  does not reflect the sequence of events when ordered by `PROCEDUREEVENTS.PROC_DT`:

```sql 
SELECT PROCEDUREEVENTS.*
FROM MIMIC2V30.PROCEDUREEVENTS
WHERE  PROCEDUREEVENTS.HADM_ID = 10001
ORDER BY PROCEDUREEVENTS.SEQUENCE_NUM ASC ;
```

![image](https://cloud.githubusercontent.com/assets/15331/7382831/367cdb96-ede3-11e4-8efe-b0ceb7f850d2.png)
