### ISSUE TITLE
How to map WFDB_Annotation().getTime() to actual timestamps?

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [mimic2/v3.0#70]
I'm trying to link some arterial blood pressure beats that I extracted from the MIMIC waveform database to events in the MIMIC clinical database. I obtained the arterial blood pressure beats using WFDB to get the beat onsets. For the beginning of a beat, I call `WFDB_Annotation().getTime()` [to get](http://www.physionet.org/physiotools/matlab/wfdb_tools/unsupported/WFDB_tools/doc/wfdb_tools/node95.html) the sample number to which the annotation "points". How can I map it to an actual timestamp (e.g. `2015-05-24 17:47:59`) so that I can link it to events in the MIMIC clinical database?

Assume that the sampling frequency is 125 Hz, and that the waveform record started at timestamp `2567-03-30 17:47:59` (which I believe we can see in the waveform header, e.g. [s00020-2567-03-30-17-47.hea](http://physionet.org/physiobank/database/mimic2wdb/matched/s00020/s00020-2567-03-30-17-47.hea)) for patient `s00020`:  if `WFDB_Annotation().getTime()`  returns `65133`, is the actual timestamp `65133/125 + 2567-03-30 17:47:59`?

**Comment by alistairewj** [comment]
To answer your question: yes, your calculation of the timestamp is correct (65133 is the time elapsed in sampled). There are a few functions provided in WFDB to help with converting between time elapsed and timestamps.

http://www.physionet.org/physiotools/wpg/strtim.htm#timstr-and-strtim

In particular, for your case of mapping elapsed time to timestamp, the following example should be useful ( this is reproduced from from http://www.physionet.org/physiotools/wpg/wpg_48.htm#Example-3 ):

```c++
 1  #include <stdio.h>
 2  #include <wfdb/wfdb.h>
 3
 4  main(argc, argv)
 5  int argc;
 6  char *argv[];
 7  {
 8      WFDB_Anninfo a;
 9      WFDB_Annotation annot;
10
11      if (argc < 3) {
12          fprintf(stderr, "usage: %s annotator record\n", argv[0]);
13          exit(1);
14      }
15      a.name = argv[1]; a.stat = WFDB_READ;
16      (void)sampfreq(argv[2]);
17      if (annopen(argv[2], &a, 1) < 0) exit(2);
18      while (getann(0, &annot) == 0)
19          printf("%s (%ld) %s %d %d %d %s\n",
20                 timstr(-(annot.time)),
21                 annot.time,
22                 annstr(annot.anntyp),
23                 annot.subtyp, annot.chan, annot.num,
24                 (annot.aux != NULL && *annot.aux > 0) ?
25                  annot.aux+1 : "");
26      exit(0);
27  }
```

(See http://physionet.org/physiotools/wfdb/examples/example3.c for a copy of this program.)

Notes:

Line 16:
The invocation of sampfreq here sets the internal variables needed by timstr below.

Line 20:
This line gives the annotation time as a time of day. If the base time is omitted in the header file, or if we used timstr(annot.time) instead, we would obtain the elapsed time from the beginning of the record.

Lines 24–25:
This expression evaluates to an empty string unless the aux string is non-empty. It makes the assumption that aux is a printable ASCII string; the printable part follows the length byte.

**Comment by Franck-Dernoncourt** [comment]
Moved to Stack Exchange: [How to map WFDB_Annotation().getTime() to actual timestamps?](http://opendata.stackexchange.com/q/6402/1652)

@alistairewj  can you post your answer there?
