### ISSUE TITLE
In which cases is a waveform recording split into two recordings in MIMIC WDB 2v3?

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [mimic2/v3.0#72]
http://physionet.org/physiobank/database/mimic2wdb/ lists two cases where one waveform recording is split into two recordings:

- a patient was admitted more than once to any of the study ICUs during the study period
- gaps of an hour or more have been split into separate records

Are there other cases that cause a waveform recording to be split into two recordings in MIMIC WDB 2v3?

**Comment by alistairewj** [comment]
Technically, those are the only two reasons for a waveform record to be split into two segments. However the actual underlying reason why the gap occurred varies. Does this answer your question?

**Comment by Franck-Dernoncourt** [comment]
It does, thanks!

**Comment by Franck-Dernoncourt** [comment]
Moved to Stack Exchange: [In which cases is a waveform recording split into two recordings in MIMIC WDB 2v3?](http://opendata.stackexchange.com/q/6421/1652)

@alistairewj  can you please post your answer there?

**Comment by alistairewj** [comment]
Done.
