### ISSUE TITLE
Under which license are the documentation and the code?

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [mimic2/v3.0#77]
I may have missed it but I don't see any license specified for either the code or the documentation. I guess there could be a default license that could be overridden in source file headers or documentation page footers.

**Comment by tompollard** [comment]
Thanks Franck, good point. I have added an MIT license at: https://github.com/mimic2/v3.0/blob/gh-pages/LICENSE.md. Let me know if you think the license needs further clarification, otherwise I'll mark the issue as resolved.

Tom

**Comment by tompollard** [comment]
See also issues #78 and #79 (providing a suggestion citation for the guidelines).

**Comment by tompollard** [comment]
MIT license added. Resolved.

**Comment by Franck-Dernoncourt** [comment]
Sounds good!
