### ISSUE TITLE
What is NOTEEVENTS.ELEM_ID?

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [mimic2/v3.0#89]
The [documentation](http://mimic2.github.io/v3.0/dat/noteevents.html) describes `NOTEEVENTS.ELEM_ID` as the "*Element ID of each note*". What is it?

It seems to be always `NULL`:
```sql
-- Returns 0 row
SELECT COUNT(*) FROM MIMIC2V30.NOTEEVENTS WHERE ELEMID IS NOT NULL;
```

(also, in the database there is a missing underscore: `ELEMID` instead of `ELEM_ID`)

**Comment by tompollard** [comment]
Not a satisfying answer, but see issue #15. We'll retain the ```ELEM_ID``` mapping internally in case it is needed, but it will be removed from the public release.

**Comment by Franck-Dernoncourt** [comment]
Whoops thanks sorry I didn't see https://github.com/mimic2/v3.0/issues/15.

**Comment by tompollard** [comment]
No problem! The issue wouldn't have shown up in a search for ```ELEM_ID``` and even if you had seen it, it doesn't really answer the underlying question. If we find the origin of the column, I'll let you know...
