### ISSUE TITLE
Survival Censor Time

### ISSUE THREAD

**Issue by tnaumann** [mimic2/v3.0#92]
If the last patient discharge in MIMIC2V30 happened on 31 October 2012, and the SSN records were checked in February 2013, this would mean that the "censor time" for survival in those patients with no `DOD` is 93 days, correct?

``` sql
select distinct a.subject_id, a.hadm_id, 
    case when d.dod is null then 93
         else round((extract(day from d.dod-a.disch_dt)+extract(hour from d.dod-a.disch_dt)/24),2) end
         as survival_days
from mimic2v30.d_patients d, mimic2v30.admissions a
where d.subject_id = a.subject_id

```

**Comment by Franck-Dernoncourt** [comment]
That's my understanding (making the conservative assumption that the SSN records were last checked on on February *1*, 2013).

**Comment by tnaumann** [comment]
Thanks, Franck. 

@mghassem FYI.

**Comment by alistairewj** [comment]
The last recorded death in the social security data is February 28th, 2013. So you can extend the survival time by the month of February.

**Comment by tnaumann** [comment]
Thanks; changed to 156 days.
