### ISSUE TITLE
Inferring ventilation level/time based on structured data 

### ISSUE THREAD

**Issue by mghassem** [mimic2/v3.0#97]
How do we interpret new ventilator billing codes that are reported on a per-day basis to find the time and type of ventilation a person was one, and when a weaning might have been attempted? I think Alistair had said that the new billing codes are more reliable because the FiO2 settings we've traditionally queried could be high flow nasal specs or a NRB. If there really is no minimum time duration needed in order to bill for ventilation, is there some reasonable way to backtrack to start and stop times within some window of certainty?

E.g. for SID 35, there are three ventilation billing codes in the new dataset, making it look like there was a two-day wean on May 5/6.
35 04-MAY-3115 00.00.00 VENT MGMT
35 07-MAY-3115 00.00.00 VENT MGMT
35 08-MAY-3115 00.00.00 VENT MGMT;SUBSQ DAYS(INVASIVE)

However, if you extract ventilator settings (i.e., "select * from chartevents where subject_id = 35 and (itemid = 3420 or itemid = 190) order by charttime") from 2v26 as recommended by the FAQ, it seems like the patient is constantly ventilated.
SID Charttime Value1 Stopped
35 04-May-3115 13:00:00 1 NotStopd
35 04-May-3115 14:00:00 0.6 NotStopd
35 04-May-3115 17:00:00 0.4 NotStopd
35 04-May-3115 18:18:00 0.4 NotStopd
35 04-May-3115 19:40:00 0.4 NotStopd
35 04-May-3115 20:40:00 0.4 NotStopd
35 04-May-3115 22:20:00 0.5 NotStopd
35 05-May-3115 0:30:00 0.7 NotStopd
35 05-May-3115 1:00:00 0.8 NotStopd
35 05-May-3115 2:00:00 0.8 NotStopd
35 05-May-3115 2:30:00 0.6 NotStopd
35 05-May-3115 3:00:00 0.4 NotStopd
35 05-May-3115 4:00:00 0.4 NotStopd
35 05-May-3115 6:00:00 0.6 NotStopd
35 05-May-3115 8:00:00 0.8 NotStopd
35 05-May-3115 11:00:00 0.6 NotStopd
35 05-May-3115 15:00:00 0.6 NotStopd
35 05-May-3115 19:00:00 0.6 NotStopd
35 05-May-3115 23:00:00 0.5 NotStopd
35 06-May-3115 3:00:00 0.5 NotStopd
35 06-May-3115 7:00:00 0.5 NotStopd
35 06-May-3115 14:00:00 0.5 NotStopd
35 06-May-3115 16:30:00 0.5 NotStopd
35 06-May-3115 17:00:00 0.7 NotStopd
35 06-May-3115 20:00:00 0.5 NotStopd
35 06-May-3115 23:00:00 0.5 NotStopd
35 07-May-3115 13:27:00 1 NotStopd
35 07-May-3115 14:00:00 0.6 NotStopd
35 07-May-3115 15:00:00 0.4 NotStopd
35 07-May-3115 16:00:00 0.5 NotStopd
35 07-May-3115 16:30:00 0.6 NotStopd
35 07-May-3115 17:00:00 0.5 NotStopd
35 07-May-3115 19:00:00 0.5 NotStopd
35 07-May-3115 23:00:00 0.5 NotStopd
35 08-May-3115 3:28:00 0.5 NotStopd
35 08-May-3115 7:00:00 0.5 NotStopd
35 08-May-3115 9:40:00 0.6 NotStopd
35 08-May-3115 12:00:00 0.6 NotStopd
35 08-May-3115 16:00:00 0.6 NotStopd
35 08-May-3115 19:00:00 0.6 NotStopd
35 08-May-3115 23:00:00 0.6 NotStopd
35 08-May-3115 23:43:00 0.6 NotStopd
35 09-May-3115 0:00:00 0.6 NotStopd
35 09-May-3115 3:00:00 0.6 NotStopd

Looking at 35's discharge summary, it seems like the patient was indeed weaned sometime on May 4th, but then re-vented on May 7th.

    "... taken to the operating room on [**3115-5-4**] where she underwent an AVR ... She was extubated and weaned form her vasoactive drips later that same day... On [**5-7**] she was reintubated and ..."

For timing, the first nursing note from 04-MAY-15 05.37 PM already claims "no vent".
The next note that mentions "reintubated during ppm for reapiratory distress" is on 07-MAY-15 05.28 PM.
I can't see any direct mention of extubation on 08-MAY notes, but the first note the next day on 09-MAY-15 06.56.00 AM states "nasal cannula and face tent".

If I wanted to identify automatically the times of invasive ventilation, non-invasive ventilation, an non-ventilated, is there any way we can we reliably extract this from a combination of the structured data we have?

**Comment by mghassem** [comment]
Update. 

Leo said that patients get put on oxygen via nasal cannula/mask immediately after extubation, and this should be in the structured data somehow. I checked 2v26, but there's only one chartitem (itemid = 182) that's got a label of "Extubation Date" - there's a matching label "Intubation Date" (itemid = 418) - but its never recorded in chartevents.

Would the same be true for pressor administration [e.g. med.itemid in (46,47,120,43,307,44,119,309,51,127,128) from mimic2v26.medevents]? If you look only at this data, without some other structure information, there are some people with what *looks like* a constant intervention, where they have only gaps of 2/3 hours in those itemids. If a patient appears to have pressors in their record all the way until the end, does that mean that they were discharged to the floor/sent out of the hospital on a pressor? Alternatively, for those that have their pressor itemids stop 3 hours before their record ends, do we believe that was a removal of pressors, or just lack of recording?

**Comment by alistairewj** [comment]
FiO2 is not exclusive to mechanical ventilation - it's a generic ventilator setting and could be used for mechanical ventilation, non-invasive ventilation, CPAP, NRBs or anything else that delivers oxygen to the patient. So I would not recommend using it to isolate mechanical ventilation (it can of course be used to determine whether a patient is having oxygen delivered of course!).

For mechanical ventilation, have you tried `ITEMID`s 720 (ventilator mode) and 722 (ventilator type) in `CHARTEVENTS`?

Regarding `MEDEVENTS` and vasopressors, this is a slightly different beast. Sometimes the drug is explicitly stopped (see the `STOPPED` column). A lot of the time a drug will be discontinued implicitly: the dose will be 0 for a prolonged period of time. When I was working with the BIDMC nurses, we agreed that if someone had a dose of 0 for a vasopressor for 4 hours, then they were certainly no longer receiving vasopressors. This is a slightly different topic though - if you want to continue this conversation I'd recommend starting a new issue explicitly stating the problem/the information you are after.

**Comment by mghassem** [comment]
Thanks Alistair! I'll work with itemids 720/722 for mechanical ventilation and ask the medevents question in a new thread.
